---

- name: Add mappings to /etc/resolv.conf
  # vagrant environment nodes
  blockinfile:
    path: /etc/resolv.conf
    block: |
       {{ item.name }} {{ item.ip }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { name: nameserver, ip: 8.8.8.8 }
    # - { ip: 10.0.1.11, name: jenkins.local }
    # - { ip: 10.0.1.15, name: gitlab.local }
    # - { ip: 10.0.1.16, name: gitlab-runner.local }
    # - { ip: 10.0.1.18, name: elk.local }
    # - { ip: 10.0.1.20, name: vuln-management.local }
    # - { ip: 10.0.1.22, name: prod.local }
  when: add_resolv_entries
