# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.define "control01" do |webtier|
      webtier.vm.box = "bento/fedora-29"
      webtier.vm.hostname = "control01"
      webtier.vm.network "private_network", ip: "192.168.45.41"
      webtier.vm.provider "virtualbox" do |vb|
          vb.name = "control01"
      end
      webtier.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "deploy.yml"
        ansible.become = true
        ansible.compatibility_mode = "2.0"
        ansible.version = "2.8.0"
      end
      webtier.vm.provision "shell", inline: <<-SHELL
        sudo dnf remove docker \
                docker-client \
                docker-client-latest \
                docker-common \
                docker-latest \
                docker-latest-logrotate \
                docker-logrotate \
                docker-selinux \
                docker-engine-selinux \
                docker-engine
          sudo dnf -y install dnf-plugins-core
          sudo dnf config-manager \
                    --add-repo \
                    https://download.docker.com/linux/fedora/docker-ce.repo
          sudo dnf install -y docker-ce \
                          docker-ce-cli \
                          containerd.io
          sudo systemctl start docker && sudo docker --version
          echo "control01 up && running"
      SHELL
    end


end
