version: '2'
services:
  wordpress:
    image: wordpress:latest
    container_name: wp
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: db_pass
  wp_db:
    image: mariadb:latest
    container_name: wp_db
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: db_pass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8181:80
