# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-compose
# https://mangolassi.it/topic/19300/install-awx-on-centos-7-with-docker

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    vb.cpus = 1
  end

      config.vm.define "awx-machine" do |webtier|
                webtier.vm.box = "bento/centos-7.6"
                webtier.vm.hostname = "awx-machine"
                webtier.vm.network "private_network", ip: "192.168.45.28"
                webtier.vm.network "forwarded_port", guest: 80, host: 80
                webtier.vm.provider "virtualbox" do |vb|
                    vb.name = "awx-machine"
                vb.memory = "4096"
                vb.cpus = 2
     end
          webtier.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "deploy.yml"
                ansible.become = true
                ansible.compatibility_mode = "2.0"
                ansible.version = "2.8.1"
          end
          webtier.vm.provision "shell", inline: <<-SHELL
            bash /vagrant/config-centos.sh
            SHELL
         end



end
