version: '3'

services:
  web:
    image: 127.0.0.1:5000/hello_world
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "80:80"
  redis:
    image: redis
