# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ansible Parallel Execution
#https://www.vagrantup.com/docs/provisioning/ansible.html


GUI = false # Enable/Disable GUI
RAM = 512 # Default memory size in MB

Vagrant.configure(2) do |config|

      N = 2
      (1..N).each do |machine_id|

              config.vm.provider "virtualbox" do |vb|
                vb.gui = GUI
                vb.memory = RAM
                vb.cpus = 1
                #vb.name = "machine#{machine_id}"
              end

              config.vm.define "machine#{machine_id}" do |machine|
                machine.vm.box = "bento/ubuntu-16.04"
                machine.vm.hostname = "machine#{machine_id}"
                machine.vm.network "private_network", ip: "192.168.45.#{10+machine_id}"

                # Only execute once the Ansible provisioner,
                # when all the machines are up and ready.
                # if machine_id == N
                    #   machine.vm.provision :ansible do |ansible|
                    #     # Disable default limit to connect to all the machines
                    #     ansible.limit = "all"
                    #     ansible.playbook = "playbook.yml"
                    #   end
                # end
              end
      end

end
