---
- hosts: cluster
  vars:
    remote_user: "devops1"
  tasks:
          - user:
                  name: "{{ remote_user }}"
                  comment: "{{ remote_user }}"
                  shell: /bin/bash
                  groups: sudo
                  append: yes
                  generate_ssh_key: yes
                  # echo "devops1badpassword" | mkpasswd --stdin --method=sha-512 --salt="devops1mybadsalt"
                  password: $6$devops1mybadsalt$vPETGtncCxJNPWRbDQ.wf539Ek.5t.GM.VAFtBME6cNEVHkLvxLnfNSuQt8.QZH.gP60Ic7ZAfZNePzOeTkET1
                  # ssh_key_type: ed25519
                  ssh_key_type: rsa
          # upload ssh key
          - authorized_key:
                  user: "{{ remote_user }}"
                  state: present
                  manage_dir: yes
                  key: "{{ lookup('file', '/home/{{ remote_user }}/.ssh/id_rsa.pub') }}"
          # configure ssh server
          - template:
                  src: ssh-setup.j2
                  dest: /etc/ssh/sshd_config
                  owner: root
                  mode: '0600'
                  validate: /usr/sbin/sshd -t -f %s
                  backup: yes
          # restart sshd
          - service:
                  name: sshd
                  state: restarted
