# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT
  sudo apt-get update
  echo "terraform-sandbox up"
SCRIPT
Vagrant.configure(2) do |config|
  config.vm.box_check_update = false
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "terraform-sandbox"
  config.vm.network "private_network", ip: "192.168.45.10"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "terraform-sandbox"
    vb.memory = "512"
    vb.cpus = 1
  end
  config.vm.provision "shell", inline: $script, privileged: false
end
