# -*- mode: ruby -*-
# vi: set ft=ruby :


GUI = false # Enable/Disable GUI
RAM = 512 # Default memory size in MB
CPU = 2
Vagrant.configure(2) do |config|

      N = 2
      (1..N).each do |machine_id|

              config.vm.provider "virtualbox" do |vb|
                vb.gui = GUI
                vb.memory = RAM
                vb.cpus = CPU
                #vb.name = "machine#{machine_id}"
              end

              config.vm.define "machine#{machine_id}" do |machine|
                machine.vm.box = "bento/ubuntu-16.04"
                machine.vm.hostname = "machine#{machine_id}"
                machine.vm.network "private_network", ip: "192.168.45.#{10+machine_id}"

              end
      end

end
