# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://research.cs.wisc.edu/htcondor/instructions/el/7/stable/
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    vb.cpus = 2
  end

  config.vm.define "control-machine1" do |webtier|
	  webtier.vm.box = "bento/scientific-7.6"
    webtier.vm.hostname = "control-machine1"
    webtier.vm.network "private_network", ip: "192.168.45.25"
    webtier.vm.provider "virtualbox" do |vb|
        vb.name = "control-machine1"
    end
    webtier.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "deploy.yml"
    ansible.become = true
    ansible.compatibility_mode = "2.0"
    ansible.version = "2.8.2"
    end
    webtier.vm.provision "shell", inline: <<-SHELL
          wget https://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
          rpm --import RPM-GPG-KEY-HTCondor
          cd /etc/yum.repos.d && sudo wget https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo
          sudo yum install -y condor
          sudo systemctl start condor
          sudo systemctl enable condor
          sudo systemctl status condor
    SHELL
  end
end
