# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.define "control01" do |webtier|
      webtier.vm.box = "bento/centos-7.6"
      webtier.vm.hostname = "control01"
      webtier.vm.network "private_network", ip: "192.168.45.41"
      webtier.vm.provider "virtualbox" do |vb|
          vb.name = "control01"
      end
      webtier.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "deploy.yml"
        ansible.become = true
        ansible.version = "2.8.0"
      end
      webtier.vm.provision "shell", inline: <<-SHELL
          sudo yum remove docker \
                      docker-client \
                      docker-client-latest \
                      docker-common \
                      docker-latest \
                      docker-latest-logrotate \
                      docker-logrotate \
                      docker-engine
          sudo yum install -y yum-utils \
                        device-mapper-persistent-data \
                        lvm2
          sudo yum-config-manager \
                            --add-repo \
                            https://download.docker.com/linux/centos/docker-ce.repo
          sudo yum install -y docker-ce \
                          docker-ce-cli \
                          containerd.io
          sudo systemctl start docker && sudo docker --version
          echo "control01 up && running"
      SHELL
    end


end
