# -*- mode: ruby -*-
# vi: set ft=ruby :
$docker_script = <<SCRIPT
# Get Docker Engine - Community for CentOS
# https://docs.docker.com/install/linux/docker-ce/centos/
sudo yum remove docker \
docker-client \
docker-client-latest \
docker-common \
docker-latest \
docker-latest-logrotate \
docker-logrotate \
docker-engine
sudo yum install -y yum-utils \
device-mapper-persistent-data \
lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce \
docker-ce-cli \
containerd.io
sudo systemctl enable docker
sudo systemctl start docker && sudo docker --version
sudo usermod -aG docker vagrant # add user to the docker group
# Install Docker Compose
# https://docs.docker.com/compose/install/
# sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose && sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
# sudo docker-compose --version
SCRIPT
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.define "control01" do |webtier|
      webtier.vm.box = "bento/centos-7.6"
      webtier.vm.hostname = "control01"
      webtier.vm.network "private_network", ip: "192.168.45.41"
      webtier.vm.provider "virtualbox" do |vb|
          vb.name = "control01"
      end
      webtier.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "deploy.yml"
        ansible.become = true
        ansible.compatibility_mode = "2.0"
        ansible.version = "2.8.4"
      end
      webtier.vm.provision "shell", inline: $docker_script, privileged: false
      webtier.vm.provision "shell", inline: <<-SHELL
          hostnamectl status
      SHELL
    end


end
